commit changes
Signed-off-by: Kevin Huntly <kmhuntly@gmail.com>

diff --git a/bin/rotatefiles b/bin/rotatefiles
--- a/bin/rotatefiles
+++ b/bin/rotatefiles
@@ -28,16 +28,13 @@ declare FUNCTION_NAME="${CNAME}#startup";
 declare SCRIPT_ROOT="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && printf "%s" "${PWD}")")";
 declare DEFAULT_CONFIG_FILE="${SCRIPT_ROOT}/config/$(basename "${CNAME}" ".sh")/$(basename "${CNAME}" ".sh").properties";
 
-if [[ -r "${SCRIPT_ROOT}/lib/system/logging.sh" ]] && [[ -s "${SCRIPT_ROOT}/lib/system/logging.sh" ]]; then
-    # shellcheck source=../../lib/system/logging.sh
-    source "${SCRIPT_ROOT}/lib/system/logging.sh";
-elif [[ -r "${HOME}/lib/system/logging.sh" ]] && [[ -s "${HOME}/lib/system/logging.sh" ]]; then
-    # shellcheck source=${HOME}/lib/system/logging.sh
-    source "${HOME}/lib/system/logging.sh";
+if [[ -r "${HOME}/lib/system/logging.sh" ]] && [[ -s "${HOME}/lib/system/logging.sh" ]]; then
+    # shellcheck source=/home/khuntly/lib/system/logging.sh
+    source "${HOME}/lib/system/logging.sh"; ## if its here, override the above and use it
 elif [[ -r "/usr/local/bin/logging.sh" ]] && [[ -s "/usr/local/bin/logging.sh" ]]; then
-    source "/usr/local/bin/logging.sh";
+    source "/usr/local/bin/logging.sh"; ## if its here, use it
 else
-    printf "\e[00;31m%s\e[00;32m\n" "Unable to load logger. No logging enabled!" >&2;
+    printf "\[\e[91m\]%s\n" "Unable to load logger. No logging enabled!" >&2;
 fi
 
 if [[ -n "${LOGGING_LOADED}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]] && [[ -n "${ENABLE_PERFORMANCE}" ]] && [[ "${ENABLE_PERFORMANCE}" == "${_TRUE}" ]]; then
